services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: "hw6"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: