version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: p_user
      POSTGRES_PASSWORD: p_password
    ports:
      - "5432:5432"
    volumes:
      - data_in_postgres:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  data_in_postgres: